twitter-ko-kafka-service:
  twitter-keywords:
    - Engineer
    - Microservices
    - Data
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello Microservices
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000